### ISSUE TITLE
#6796 test failure 1: `into datetime` Parse error

### ISSUE THREAD

**Issue by dandavison** [dandavison/nushell#10]
**This is not an issue in the main nushell repo**

This issue is for a class of test failures currently affecting https://github.com/nushell/nushell/pull/6796

## Failure:
```
thread 'date::format::test::test_examples' panicked at 'test parse error in `'2021-10-22 20:00:12 +01:00' | into datetime | date format`: ExtraPositional("into ", Span { start: 36, end: 44 })', crates/nu-command/src/exampl
e_test.rs:274:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: nu_command::example_test::test_examples::parse
             at ./src/example_test.rs:274:13
   3: nu_command::example_test::test_examples::eval_pipeline_without_terminal_expression
             at ./src/example_test.rs:312:34
   4: nu_command::example_test::test_examples::check_example_input_and_output_types_match_command_signature
             at ./src/example_test.rs:111:17
   5: nu_command::example_test::test_examples::test_examples
             at ./src/example_test.rs:40:17
   6: nu_command::example_test::test_examples
             at ./src/example_test.rs:6:5
   7: nu_command::date::format::test::test_examples
             at ./src/date/format.rs:482:9
   8: nu_command::date::format::test::test_examples::{{closure}}
             at ./src/date/format.rs:479:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

Note the trailing space character in `"into "`.

## Repro
```
git remote add dandavison git@github.com:dandavison/nushell.git
git fetch dandavison input-output-syntax-shape
git checkout dandavison/input-output-syntax-shape

cargo test -p nu-command date::format::test::test_examples
```

**Comment by dandavison** [comment]
So here, in the test, when it attempts to parse

```
'2021-10-22 20:00:12 +01:00' | into datetime
```

It produces this error:

```
ExtraPositional("into ", Span { start: 36, end: 44 })
```

This is the same as the error we get if we ask it to parse a non-existent `into` subcommand, e.g.

```
ast "'1' | into datetimeX"
```

```
error: Some(
    ExtraPositional(
        "into ",
        Span {
            start: 78612,
            end: 78621,
        },
    ),
)
```

However, in my test, I am giving it `into datetime` which should be a valid `into` subcommand.

**Comment by dandavison** [comment]
This is a bug in nushell `main` branch and unrelated to https://github.com/nushell/nushell/pull/6796. See https://github.com/nushell/nushell/pull/7031
