### ISSUE TITLE
#6796 test failure 2: `ExternalNotSupported`

### ISSUE THREAD

**Issue by dandavison** [dandavison/nushell#11]
**This is not an issue in the main nushell repo**

This issue is for a class of test failures currently affecting https://github.com/nushell/nushell/pull/6796

## Failure:

```
thread 'filters::lines::test::test_examples' panicked at 'test eval error in `TODO`: ExternalNotSupported(Span { start: 11, end: 15 })', crates/nu-command/src/example_test.rs:302:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: nu_command::example_test::test_examples::eval_block
             at ./src/example_test.rs:302:25
   3: nu_command::example_test::test_examples::eval_pipeline_without_terminal_expression
             at ./src/example_test.rs:320:26
   4: nu_command::example_test::test_examples::check_example_input_and_output_types_match_command_signature
             at ./src/example_test.rs:111:17
   5: nu_command::example_test::test_examples::test_examples
             at ./src/example_test.rs:40:17
   6: nu_command::example_test::test_examples
             at ./src/example_test.rs:6:5
   7: nu_command::filters::lines::test::test_examples
             at ./src/filters/lines.rs:268:9
   8: nu_command::filters::lines::test::test_examples::{{closure}}
             at ./src/filters/lines.rs:265:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

## Repro:
```
git remote add dandavison git@github.com:dandavison/nushell.git
git fetch dandavison input-output-syntax-shape
git checkout dandavison/input-output-syntax-shape

cargo test -p nu-command filters::lines::test::test_examples
```

**Comment by dandavison** [comment]
This was caused by a combination of some commands accidentally missing their `test_examples` test, and some externals not being included in the `working_set` set in `example_test.rs`: I had added the missing tests to the commands, and then started seeing these errors because I hadn't added things like `Char` to the `working_set`.
