### ISSUE TITLE
#6796 test failure 3: span mismatches

### ISSUE THREAD

**Issue by dandavison** [dandavison/nushell#12]
**This is not an issue in the main nushell repo**

This issue is for a class of test failures currently affecting https://github.com/nushell/nushell/pull/6796

## Failure:
```
thread 'filters::merge::test::test_examples' panicked at 'assertion failed: `(left == right)`
  left: `List { vals: [Record { cols: ["columnA", "columnB"], vals: [String { val: "A0*", span: Span { start: 176, end: 181 } }, String { val: "B0", span: Span { start: 152, end: 154 } }], span: Span { start: 159, end: 164
 } }], span: Span { start: 0, end: 0 } }`,
 right: `List { vals: [Record { cols: ["ColumnA", "ColumnB"], vals: [String { val: "A0*", span: Span { start: 0, end: 0 } }, String { val: "B0", span: Span { start: 0, end: 0 } }], span: Span { start: 0, end: 0 } }], span:
 Span { start: 0, end: 0 } }`: The example result differs from the expected value', crates/nu-command/src/example_test.rs:225:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:218:23
   3: core::panicking::assert_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:181:5
   4: nu_command::example_test::test_examples::check_example_evaluates_to_expected_output
             at ./src/example_test.rs:225:13
   5: nu_command::example_test::test_examples::test_examples
             at ./src/example_test.rs:49:13
   6: nu_command::example_test::test_examples
             at ./src/example_test.rs:6:5
   7: nu_command::filters::merge::test::test_examples
             at ./src/filters/merge.rs:266:9
   8: nu_command::filters::merge::test::test_examples::{{closure}}
             at ./src/filters/merge.rs:263:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

Note the trailing space character in `"into "`.

## Repro
```
git remote add dandavison git@github.com:dandavison/nushell.git
git fetch dandavison input-output-syntax-shape
git checkout dandavison/input-output-syntax-shape

cargo test -p nu-command filters::merge::test::test_examples
```

**Comment by sophiajt** [comment]
For this one, a Span(0, 0) would be something that is in a pretty broken state. In theory, no valid Value should ever have a 0, 0 span. That said there are still a few places that have them.

Would need to take a closer look, but the first places I'd look would be around anything in the parser or eval that's creating a 0, 0 span and see if it's somehow related.

**Comment by rgwood** [comment]
I think this might just be a string case issue, unrelated to the spans: `["columnA", "columnB"]` vs `["ColumnA", "ColumnB"]`

If I fix the case for the column names in the example, the test passes.

**Comment by dandavison** [comment]
Ah-ha, thank you @rgwood! :)
