### ISSUE TITLE
#6796 test failure 4: UnknownState("internal error: let statement unparseable"

### ISSUE THREAD

**Issue by dandavison** [dandavison/nushell#13]
**This is not an issue in the main nushell repo**

This issue is for a class of test failures currently affecting https://github.com/nushell/nushell/pull/6796

## Failure:
```
thread 'filters::where_::test::test_examples' panicked at 'test parse error in `let a = {$in > 3}; [1, 2, 5, 6] | where -b $a`: UnknownState("internal error: let statement unparseable", Span { start: 0, end: 17 })', crates
/nu-command/src/example_test.rs:274:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: nu_command::example_test::test_examples::parse
             at ./src/example_test.rs:274:13
   3: nu_command::example_test::test_examples::eval_pipeline_without_terminal_expression
             at ./src/example_test.rs:312:34
   4: nu_command::example_test::test_examples::check_example_input_and_output_types_match_command_signature
             at ./src/example_test.rs:111:17
   5: nu_command::example_test::test_examples::test_examples
             at ./src/example_test.rs:40:17
   6: nu_command::example_test::test_examples
             at ./src/example_test.rs:6:5
   7: nu_command::filters::where_::test::test_examples
             at ./src/filters/where_.rs:277:9
   8: nu_command::filters::where_::test::test_examples::{{closure}}
             at ./src/filters/where_.rs:274:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

Note the trailing space character in `"into "`.

## Repro
```
git remote add dandavison git@github.com:dandavison/nushell.git
git fetch dandavison input-output-syntax-shape
git checkout dandavison/input-output-syntax-shape

cargo test -p nu-command filters::where_::test::test_examples
```

**Comment by sophiajt** [comment]
does the issue also repro with `let a = {$in > 3};` or `let a = {$in > 3}`?

Could help narrow what parts of the parser might be having issues.

**Comment by dandavison** [comment]
Thanks for looking at these @jntrnr.

Yes it does repro the same with both of those. E.g.
```
                example: "let a = {$in > 3};",
```

**Comment by dandavison** [comment]
Narrowing down a bit more, the problem here is that [here in `parse_let`](https://github.com/nushell/nushell/blob/766d1ef3742489d1fcf74cc478d919d2b506cefb/crates/nu-parser/src/parse_keywords.rs#L2754)

```
working_set.find_decl(b"let", &Type::Any)
```

is returning `None`.

Perhaps something to do with the way I'm setting up `engine_state` in [test_examples](https://github.com/dandavison/nushell/blob/input-output-syntax-shape/crates/nu-command/src/example_test.rs#L26)?

**Comment by dandavison** [comment]
This was simply caused by `Let` not being in the `working_set` in `example_test.rs`. We didn't notice, because `where` was accidentally missing its tests.
